### ISSUE TITLE
rls-vscode seem to have issues compiling async-attributes

### ISSUE THREAD

**Issue by Gozala** [async-rs/async-attributes#14]
It appears that projects that depend on `async-attributes` break [rust-lang/rls-vscode#755](https://github.com/rust-lang/rls-vscode/issues/755). I am not exactly how rls-vscode is compiling because I am unable to reproduce issue by running `cargo check` / `cargo build` however I do see following error from vscode output:

```
{"message":"cannot lex `source_file` without source: /Users/gozala/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-1.0.3/src/lib.rs","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror: internal compiler error\u001b[0m\u001b[0m\u001b[1m: cannot lex `source_file` without source: /Users/gozala/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-1.0.3/src/lib.rs\u001b[0m\n\n"}
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:880:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-apple-darwin

note: compiler flags: -C prefer-dynamic -C debuginfo=2 --crate-type proc-macro

note: some of the compiler flags provided by cargo are hidden

{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m: aborting due to previous error\u001b[0m\n\n"}
```

I am reporting this issue here because it appears that issue is with `async-attributes`. 

I am not seeing same error if I just use `quote` instead `async-attributes` so I am not sure what is the problem.

**Comment by yoshuawuyts** [comment]
@Gozala this seems like an issue with rls-vscode, and probably not something we can do much to solve here. My understanding is that rls-vscode is not actively developed anymore with most of the effort going into rust-analyzer instead. To my knowledge rust-analyzer doesn't have the same problems, and I'd recommend switching to that instead.

It's a bit of an unfortunate answer, but we don't really have the resources on our side to help solve the issue for rls-vscode.

**Comment by Gozala** [comment]
Thanks @yoshuawuyts, turns out it was neither of two and problem was this https://github.com/rust-lang/rust/issues/69933

 Thanks for letting me know about efforts beings shifted towards rust-analyzer, I’ll give that a try.
