### ISSUE TITLE
Backtraces are munged by #[async_attributes::test]

### ISSUE THREAD

**Issue by Fishrock123** [async-rs/async-attributes#23]
I mentioned this to @yoshuawuyts in a call but figured I should also open an issue here.

Error backtraces are somehow munged when the panic occurs from the handler in this `test` attribute.
The backtrace will point to e.g. `#[async_std::test]` rather than the line of the error, and useful location information is usually completely missing from `BACKTRACE=short`. One has to know how to search through a backtrace to extract error origin location which is not at all ideal for rapid test development.

I don't have an example offhand, as the issue is bad enough that I've changed all my internal test helpers and error propagations to use `unwrap()`.

~~In fact, we also use this error type on our test cases:~~
```rust
/// A Wrapper around [`Infalliable`](std::convert::Infallible) to force test cases to use `.unwrap()`.
///
/// This is useful because `.unwrap()` provides better stacktraces than propogating errors to [`#[async_std::test]`](async_std::test).
pub type MustUnwrap = Result<(), std::convert::Infallible>;
```
Edit: _it is only now that I realize that this `MustUnwrap` type is functionally identical to `()`. :facepalm:_

**Comment by Fishrock123** [comment]
Ok turns out I have been wrong, however, the following things are true:

- Error returns have more complex backtraces.
- Both errors and panics from within a test helper _function_ cause the location to point to the helper.
    - This means that digging through the backtraces is necessary to find the location, exacerbating the above backtrace thing.
    
I think the end result of this is that the test helpers we have written will be switched over to be macros.

**Comment by Fishrock123** [comment]
See also https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/test.20error.20location.20output

**Comment by sagudev** [comment]
On code:
```rust
#[async_attributes::test]
#[should_panic]
async fn panic_test() {
    assert!(false);
}
```
shows backtrace:
```
...
  33: test::panic_test
             at ./tests/test.rs:1:1
  34: test::panic_test::{{closure}}
             at ./tests/test.rs:1:1
  35: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  36: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test panic_test - should panic ... ok
```
Backtrace is showing panicking on line 1 although it is on line 4.

**Comment by sagudev** [comment]
If I manually extend macro, so I got code:
```rust
#[test]
#[should_panic]
fn panic_test() {
    async_std::task::block_on(async {
        assert!(false);
    })
}
```
I got backtrace:
```
  33: test::panic_test
             at ./tests/test.rs:4:5
  34: test::panic_test::{{closure}}
             at ./tests/test.rs:3:1
  35: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  36: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test panic_test - should panic ... ok
```
which still does not point at line 5, so maybe the problem is also in `block_on`?
